#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PharmacyStoreModel;


namespace PharmacyStoreModel	
{
	[Table("SY_STORE")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class SY_STORE
	{
		private int _id;
		[Column("Id", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_id")]
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private string _website;
		[Column("Website", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_website")]
		public virtual string Website 
		{ 
		    get
		    {
		        return this._website;
		    }
		    set
		    {
		        this._website = value;
		    }
		}
		
		private string _storeTelephone;
		[Column("StoreTelephone", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_storeTelephone")]
		public virtual string StoreTelephone 
		{ 
		    get
		    {
		        return this._storeTelephone;
		    }
		    set
		    {
		        this._storeTelephone = value;
		    }
		}
		
		private string _storeTaxNo;
		[Column("StoreTaxNo", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_storeTaxNo")]
		public virtual string StoreTaxNo 
		{ 
		    get
		    {
		        return this._storeTaxNo;
		    }
		    set
		    {
		        this._storeTaxNo = value;
		    }
		}
		
		private string _storeName;
		[Column("StoreName", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_storeName")]
		public virtual string StoreName 
		{ 
		    get
		    {
		        return this._storeName;
		    }
		    set
		    {
		        this._storeName = value;
		    }
		}
		
		private string _storeFax;
		[Column("StoreFax", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_storeFax")]
		public virtual string StoreFax 
		{ 
		    get
		    {
		        return this._storeFax;
		    }
		    set
		    {
		        this._storeFax = value;
		    }
		}
		
		private string _storeAddress;
		[Column("StoreAddress", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_storeAddress")]
		public virtual string StoreAddress 
		{ 
		    get
		    {
		        return this._storeAddress;
		    }
		    set
		    {
		        this._storeAddress = value;
		    }
		}
		
		private string _email;
		[Column("Email", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_email")]
		public virtual string Email 
		{ 
		    get
		    {
		        return this._email;
		    }
		    set
		    {
		        this._email = value;
		    }
		}
		
		private int _userId;
		[Column("UserId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_userId")]
		public virtual int UserId 
		{ 
		    get
		    {
		        return this._userId;
		    }
		    set
		    {
		        this._userId = value;
		    }
		}
		
		private SY_USER _sY_USER;
		[ForeignKeyAssociation(ConstraintName = "FK_dbo.SY_STORE_dbo.SY_USER_UserId", SharedFields = "UserId", TargetFields = "Id")]
		[Storage("_sY_USER")]
		public virtual SY_USER SY_USER 
		{ 
		    get
		    {
		        return this._sY_USER;
		    }
		    set
		    {
		        this._sY_USER = value;
		    }
		}
		
		private IList<LS_DOCTOR> _lS_DOCTORs = new List<LS_DOCTOR>();
		[Collection(InverseProperty = "SY_STORE")]
		[Storage("_lS_DOCTORs")]
		public virtual IList<LS_DOCTOR> LS_DOCTORs 
		{ 
		    get
		    {
		        return this._lS_DOCTORs;
		    }
		}
		
	}
}
