#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PharmacyStoreModel;


namespace PharmacyStoreModel	
{
	[Table("LS_DOCTOR")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class LS_DOCTOR
	{
		private int _id;
		[Column("Id", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_id")]
		public virtual int Id 
		{ 
		    get
		    {
		        return this._id;
		    }
		    set
		    {
		        this._id = value;
		    }
		}
		
		private int _storeId;
		[Column("StoreId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_storeId")]
		public virtual int StoreId 
		{ 
		    get
		    {
		        return this._storeId;
		    }
		    set
		    {
		        this._storeId = value;
		    }
		}
		
		private string _mobile;
		[Column("Mobile", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_mobile")]
		public virtual string Mobile 
		{ 
		    get
		    {
		        return this._mobile;
		    }
		    set
		    {
		        this._mobile = value;
		    }
		}
		
		private string _fullname;
		[Column("Fullname", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_fullname")]
		public virtual string Fullname 
		{ 
		    get
		    {
		        return this._fullname;
		    }
		    set
		    {
		        this._fullname = value;
		    }
		}
		
		private string _address;
		[Column("Address", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_address")]
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
		        this._address = value;
		    }
		}
		
		private SY_STORE _sY_STORE;
		[ForeignKeyAssociation(ConstraintName = "FK_dbo.LS_DOCTOR_dbo.SY_STORE_StoreId", SharedFields = "StoreId", TargetFields = "Id")]
		[Storage("_sY_STORE")]
		public virtual SY_STORE SY_STORE 
		{ 
		    get
		    {
		        return this._sY_STORE;
		    }
		    set
		    {
		        this._sY_STORE = value;
		    }
		}
		
	}
}
